# Here we can override service configurations made at kool.services.yml
# for deployments only.
services:
    app:
      # Appications requires a special image built for deployment
      build: Dockerfile.dist

      # What port to map on deployment
      port: 3000

      # Tells kool deploy that this service accessible through the deployment url (only one service can be set to public).
      public: true
      # Tells kool to stop current deploy then start the new one
      recreate: false

      # Environment refers to a file to be used for deployment only and will make those variables
      # available for the deployed application. There are also some special keys kool deploy will
      # override in this file upon deployment, i.e the deployed database host.
      environment: kool.deploy.env
