version: '3.8'
services:
  pdf:
    image: kooldev/puppeteer:latest
    restart: unless-stopped
    command: ['yarn', 'start']
    working_dir: '/app'
    user: pptruser
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    networks:
      kool_global:
        aliases:
          - pdf_dev

networks:
  kool_global:
    external: true
    name: "${KOOL_GLOBAL_NETWORK:-kool_global}"
