name: docker

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: olegtarasov/get-tag@v2.1
      id: tagName

    - name: Build and push image
      uses: docker/build-push-action@v3
      with:
        context: ${{ steps.tagName.outputs.tag }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          kooldev/pdf:${{ steps.tagName.outputs.tag }}
          kooldev/pdf:1.0
